const WARN_THRESHOLD_MS = 1000
const MAX_TEST_DESCRIPTION_LENGTH = 100
const COUNT_SLOW_SPECS_TO_SUMMARIZE = 10

export {
    WARN_THRESHOLD_MS,
    COUNT_SLOW_SPECS_TO_SUMMARIZE,
    MAX_TEST_DESCRIPTION_LENGTH,
}
