import {BoundClassId, Notation, SymbolClassId} from "../../notation"

// TODO: POST-NOTATION-GENERATION: TESTING
//  Might be nice to test that the commas which used to be here are the commas for the symbols still/now here
//  And/or the full set of flaccos you get, at which point delete the commented out extra Flacco IDs here

const MEDIUM_NOTATION: Notation = {
    boundClassIds: [                    // Total 11
        BoundClassId.MINA_5,
        BoundClassId.MINA_16,
        BoundClassId.MINA_27,
        BoundClassId.MINA_38,
        BoundClassId.MINA_50,
        BoundClassId.MINA_61,
        BoundClassId.MINA_72,
        BoundClassId.MINA_82,
        BoundClassId.MINA_92,
        BoundClassId.MINA_105,
        BoundClassId.MINA_116,
    ] as BoundClassId[],
    symbolClassIds: [                        // Extra 2 flaccos, total 13
        SymbolClassId.NULL,
        SymbolClassId.RIGHT_SCROLL,
        SymbolClassId.DOUBLE_SCROLL,
        SymbolClassId.BOATHOOK_AND_SCROLL,
        SymbolClassId.LEFT_BARB,
        SymbolClassId.RIGHT_ARC,
        SymbolClassId.LEFT_ARC,
        SymbolClassId.ARC_AND_SCROLL,
        SymbolClassId.DOUBLE_LEFT_BARB,
        SymbolClassId.BARB_AND_ARC,
        SymbolClassId.DOUBLE_BARB,
        // SymbolClassId.DOUBLE_ARC,
        // SymbolClassId.ARC_AND_BARB,
    ] as SymbolClassId[],
}

const HIGH_NOTATION: Notation = {
    boundClassIds: [                    // Total 27
        BoundClassId.MINA_2,
        BoundClassId.MINA_9,
        BoundClassId.MINA_13,
        BoundClassId.MINA_18,
        BoundClassId.MINA_22,
        BoundClassId.MINA_27,
        BoundClassId.MINA_31,
        BoundClassId.MINA_35,
        BoundClassId.MINA_38,
        BoundClassId.MINA_41,
        BoundClassId.MINA_46,
        BoundClassId.MINA_53,
        BoundClassId.MINA_58,
        BoundClassId.MINA_63,
        BoundClassId.MINA_66,
        BoundClassId.MINA_70,
        BoundClassId.MINA_76,
        BoundClassId.MINA_78,
        BoundClassId.MINA_81,
        BoundClassId.MINA_85,
        BoundClassId.MINA_92,
        BoundClassId.MINA_97,
        BoundClassId.MINA_101,
        BoundClassId.MINA_106,
        BoundClassId.MINA_110,
        BoundClassId.MINA_114,
        BoundClassId.MINA_116,
    ] as BoundClassId[],
    symbolClassIds: [                        // Extra 5 flaccos, total 32
        SymbolClassId.NULL,
        SymbolClassId.LEFT_SCROLL,
        SymbolClassId.RIGHT_SCROLL,
        SymbolClassId.LEFT_BOATHOOK,
        SymbolClassId.DOUBLE_SCROLL,
        SymbolClassId.LEFT_SCROLL_AND_BOATHOOK,
        SymbolClassId.BOATHOOK_AND_SCROLL,
        SymbolClassId.RIGHT_BOATHOOK,
        SymbolClassId.DOUBLE_LEFT_BOATHOOK,
        SymbolClassId.SCROLL_AND_BOATHOOK,
        SymbolClassId.LEFT_BARB,
        SymbolClassId.LEFT_SCROLL_AND_BARB,
        SymbolClassId.RIGHT_ARC,
        SymbolClassId.SCROLL_AND_ARC,
        SymbolClassId.RIGHT_BARB,
        SymbolClassId.LEFT_ARC,
        SymbolClassId.BOATHOOK_AND_ARC,
        SymbolClassId.BARB_AND_BOATHOOK,
        SymbolClassId.ARC_AND_SCROLL,
        SymbolClassId.BOATHOOK_AND_BARB,
        SymbolClassId.DOUBLE_LEFT_BARB,
        SymbolClassId.LEFT_SCROLL_DOUBLE_LEFT_BARB,
        SymbolClassId.BARB_AND_ARC,
        SymbolClassId.ARC_AND_BOATHOOK,
        SymbolClassId.DOUBLE_BARB,
        SymbolClassId.LEFT_ARC_AND_BARB,
        SymbolClassId.LEFT_SCROLL_AND_DOUBLE_BARB,
        // SymbolClassId.RIGHT_BARB_AND_ARC,
        // SymbolClassId.DOUBLE_ARC,
        // SymbolClassId.DOUBLE_RIGHT_BARB,
        // SymbolClassId.ARC_AND_BARB,
        // SymbolClassId.LEFT_SCROLL_DOUBLE_RIGHT_BARB,
    ] as SymbolClassId[],
}

const ULTRA_NOTATION: Notation = {
    boundClassIds: [                    // Total 47
        BoundClassId.MINA_2,
        BoundClassId.MINA_3,
        BoundClassId.MINA_5,
        BoundClassId.MINA_9,
        BoundClassId.MINA_13,
        BoundClassId.MINA_14,
        BoundClassId.MINA_16,
        BoundClassId.MINA_18,
        BoundClassId.MINA_22,
        BoundClassId.MINA_24,
        BoundClassId.MINA_25,
        BoundClassId.MINA_27,
        BoundClassId.MINA_31,
        BoundClassId.MINA_35,
        BoundClassId.MINA_38,
        BoundClassId.MINA_40,
        BoundClassId.MINA_41,
        BoundClassId.MINA_46,
        BoundClassId.MINA_47,
        BoundClassId.MINA_49,
        BoundClassId.MINA_51,
        BoundClassId.MINA_53,
        BoundClassId.MINA_58,
        BoundClassId.MINA_61,
        BoundClassId.MINA_63,
        BoundClassId.MINA_64,
        BoundClassId.MINA_66,
        BoundClassId.MINA_70,
        BoundClassId.MINA_72,
        BoundClassId.MINA_74,
        BoundClassId.MINA_76,
        BoundClassId.MINA_77,
        BoundClassId.MINA_78,
        BoundClassId.MINA_81,
        BoundClassId.MINA_82,
        BoundClassId.MINA_85,
        BoundClassId.MINA_90,
        BoundClassId.MINA_92,
        BoundClassId.MINA_97,
        BoundClassId.MINA_101,
        BoundClassId.MINA_102,
        BoundClassId.MINA_105,
        BoundClassId.MINA_106,
        BoundClassId.MINA_110,
        BoundClassId.MINA_113,
        BoundClassId.MINA_114,
        BoundClassId.MINA_116,
    ] as BoundClassId[],
    symbolClassIds: [                        // Extra 8 flaccos, total 55
        SymbolClassId.NULL,
        SymbolClassId.ANTITICK_AND_LEFT_SCROLL,
        SymbolClassId.TICK,
        SymbolClassId.LEFT_SCROLL,
        SymbolClassId.RIGHT_SCROLL,
        SymbolClassId.ANTITICK_AND_LEFT_BOATHOOK,
        SymbolClassId.TICK_AND_RIGHT_SCROLL,
        SymbolClassId.LEFT_BOATHOOK,
        SymbolClassId.DOUBLE_SCROLL,
        SymbolClassId.TICK_AND_DOUBLE_SCROLL,
        SymbolClassId.LEFT_SCROLL_AND_BOATHOOK,
        SymbolClassId.ANTITICK_BOATHOOK_AND_SCROLL,
        SymbolClassId.BOATHOOK_AND_SCROLL,
        SymbolClassId.RIGHT_BOATHOOK,
        SymbolClassId.DOUBLE_LEFT_BOATHOOK,
        SymbolClassId.ANTITICK_AND_LEFT_BARB,
        SymbolClassId.SCROLL_AND_BOATHOOK,
        SymbolClassId.LEFT_BARB,
        SymbolClassId.ANTITICK_AND_LEFT_SCROLL_AND_BARB,
        SymbolClassId.TICK_AND_LEFT_BARB,
        SymbolClassId.LEFT_SCROLL_AND_BARB,
        SymbolClassId.ANTITICK_AND_RIGHT_ARC,
        SymbolClassId.RIGHT_ARC,
        SymbolClassId.TICK_AND_RIGHT_ARC,
        SymbolClassId.SCROLL_AND_ARC,
        SymbolClassId.ANTITICK_AND_LEFT_ARC,
        SymbolClassId.RIGHT_BARB,
        SymbolClassId.LEFT_ARC,
        SymbolClassId.TICK_AND_LEFT_ARC,
        SymbolClassId.BOATHOOK_AND_ARC,
        SymbolClassId.ANTITICK_ARC_AND_SCROLL,
        SymbolClassId.TICK_BOATHOOK_AND_ARC,
        SymbolClassId.BARB_AND_BOATHOOK,
        SymbolClassId.ARC_AND_SCROLL,
        SymbolClassId.BOATHOOK_AND_BARB,
        SymbolClassId.ANTITICK_AND_DOUBLE_LEFT_BARB,
        SymbolClassId.DOUBLE_LEFT_BARB,
        SymbolClassId.TICK_AND_DOUBLE_LEFT_BARB,
        SymbolClassId.LEFT_SCROLL_DOUBLE_LEFT_BARB,
        SymbolClassId.BARB_AND_ARC,
        SymbolClassId.ARC_AND_BOATHOOK,
        SymbolClassId.TICK_BARB_AND_ARC,
        SymbolClassId.ANTITICK_AND_DOUBLE_BARB,
        SymbolClassId.DOUBLE_BARB,
        SymbolClassId.LEFT_ARC_AND_BARB,
        SymbolClassId.TICK_AND_DOUBLE_BARB,
        SymbolClassId.LEFT_SCROLL_AND_DOUBLE_BARB,
        // SymbolClassId.ANTITICK_AND_DOUBLE_ARC,
        // SymbolClassId.RIGHT_BARB_AND_ARC,
        // SymbolClassId.DOUBLE_ARC,
        // SymbolClassId.TICK_AND_DOUBLE_ARC,
        // SymbolClassId.ANTITICK_ARC_AND_BARB,
        // SymbolClassId.DOUBLE_RIGHT_BARB,
        // SymbolClassId.ARC_AND_BARB,
        // SymbolClassId.LEFT_SCROLL_DOUBLE_RIGHT_BARB,
    ] as SymbolClassId[],
}

const EXTREME_NOTATION: Notation = {
    boundClassIds: Object.values(BoundClassId),     // Total 123
    symbolClassIds: Object.values(SymbolClassId),   // Extra 26 flaccos, total 149
}

const JI_NOTATION: Notation = EXTREME_NOTATION

export {
    MEDIUM_NOTATION,
    HIGH_NOTATION,
    ULTRA_NOTATION,
    EXTREME_NOTATION,
    JI_NOTATION,
}
